### ISSUE TITLE
Support values ending in !important

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/node-cssjanus#23]
Input:

``` css
.foo {
  left: 10px !important;
  float: left !important;
  padding: 1px 2px 3px 4px !important;
}
```

Expected:

``` css
.foo {
  right: 10px !important;
  float: right !important;
  padding: 1px 4px 3px 2px !important;
}
```

Actual:

``` css
.foo {
  right: 10px !important;
  float: right !important;
  padding: 1px 2px 3px 4px !important;
}
```

The `padding` rule isn't flipped.
