### ISSUE TITLE
Rule name gets flipped

### ISSUE THREAD

**Issue by MohammadYounes** [wikimedia/node-cssjanus#5]
##### LTR CSS

``` css
.content > .right:not(.ignore) {
  display:block;
}
```
##### Expected:

``` css
.content > .right:not(.ignore) {
  display:block;
}
```
##### Result:

``` css
.content > .left:not(.ignore) {
  display:block;
}
```
